### ISSUE TITLE
MISSING_ARG_APIKEY 

### ISSUE THREAD

**Issue by ravipulluri** [ideashower/ShareKit#102]
Hi,
I have a small problem.Iam using twitter service it works fine but after returning after authorization it shows a text that has to be twitted and also this extra sentence "MISSING_ARG_APIKEY".
Sharekit is awesome..
Please help me.

Ravi Pulluri.

**Comment by ideashower** [comment]
You're missing the bit.ly key.  Make sure you follow the install instructions on http://getsharekit.com/install.  You'll need to fill out the SHKConfig file.

**Comment by newacct** [comment]
I would prefer to have an option to not use Bit.ly for Twitter posts
