### ISSUE TITLE
HowTo: give action to the UIBarButtonItem to react on ShareKit (share) HELP

### ISSUE THREAD

**Issue by hoffdesign** [ideashower/ShareKit#117]
Hi Guys,

I'm trying to work with sharekit to share things on twitter and facebook etc. 
I have a UIBarButtonItem but don't know how to connect the button to do the share option?

[[UIBarButtonItem alloc] initWithBarButtonSystemItem:UIBarButtonSystemItemAction
                                              target:self
                                              action:@selector(share)]
I keep on getting 1 error on this text above... I hope someone could help me!

Thanks!

**Comment by gfontenot** [comment]
Keep reading the documentation. Immediatly below that snippet, you should see this one:

```
- (void)myButtonHandlerAction
{
    // Create the item to share (in this example, a url)
    NSURL *url = [NSURL URLWithString:@"http://getsharekit.com"];
    SHKItem *item = [SHKItem URL:url title:@"ShareKit is Awesome!"];

    // Get the ShareKit action sheet
    SHKActionSheet *actionSheet = [SHKActionSheet actionSheetForItem:item];

    // Display the action sheet
    [actionSheet showFromToolbar:navigationController.toolbar];
}
```

So, you need to actually create that `share` method yourself. The snippet above will create an URL `SHKItem`, and share it with available sharers.

**Comment by hoffdesign** [comment]
But how do I creat that share method myself? Please help!!!

**Comment by gfontenot** [comment]
I just showed you. Take that method, change the name to share, modify to your needs. It's explained pretty well in the documentation.

**Comment by hoffdesign** [comment]
I'm sorry I'm a noob in this :P but what I've done know is I've put this in my viewcontroller.m
[[UIBarButtonItem alloc] initWithBarButtonSystemItem:UIBarButtonSystemItemAction
                                              target:self
                                              action:@selector(share)]
then I pasted the following code underneath:
- (void)myButtonHandlerAction
  {
  // Create the item to share (in this example, a url)
  NSURL *url = [NSURL URLWithString:@"http://getsharekit.com"];
  SHKItem *item = [SHKItem URL:url title:@"ShareKit is Awesome!"];
  
  // Get the ShareKit action sheet
  SHKActionSheet *actionSheet = [SHKActionSheet actionSheetForItem:item];
  
  // Display the action sheet
  [actionSheet showFromToolbar:navigationController.toolbar];
  }

So what do I need to change in share? and will the UIBarButtonItem react on this code? or do I need to give it a target is so How do I do this ? Please help me! I'm sorry

**Comment by gfontenot** [comment]
There is no "share" method by default. You need to make it. That code (the snippet I posted) is an example of the method you need to use in order to send an item to ShareKit. Change `-(void)myButtonHandlerAction` to `-(void)share`. Now your button is pointing to the `share` method you just made. When you hit the button, you will create a new `SHKItem` that is a URL pointing to `http://getsharekit.com` with the title "ShareKit is Awesome!". Then, that item is sent to the `SHKActionSheet`, and displayed in your view.

This is pretty basic stuff. You may want to read up a bit on methods, and basic Objective-C development. Would probably make everything a bit easier.

**Comment by hoffdesign** [comment]
I know :P I'm still getting the error do you have Ichat? maybe you can see the project?

**Comment by gfontenot** [comment]
How about you post the error.

**Comment by hoffdesign** [comment]
Still the same error? this is the code! Error code is: /Users/pepynhoff/Desktop/tweet inspirator-1/Classes/tweet_inspiratorViewController.m:140: error: expected identifier or '(' before '[' token

And this is now my code! I want to share text in my app!

[[UIBarButtonItem alloc] initWithBarButtonSystemItem:UIBarButtonSystemItemAction
                                              target:self
                                              action:@selector(share)]
- (void)share
  {
  // Create the item to share (in this example, a url)
  NSURL *url = [NSURL URLWithString:@"http://getsharekit.com"];
  SHKItem *item = [SHKItem URL:url title:@"ShareKit is Awesome!"];
  
  // Get the ShareKit action sheet
  SHKActionSheet *actionSheet = [SHKActionSheet actionSheetForItem:item];
  
  // Display the action sheet
  [actionSheet showFromToolbar:navigationController.toolbar];
  }

**Comment by gfontenot** [comment]
You need a semi-colon at the end of the line that says `action:@selector(share)]`

**Comment by hoffdesign** [comment]
I've done this:
- (void)share
  {
  // Create the item to share (in this example, a url)
  NSURL *url = [NSURL URLWithString:@"http://getsharekit.com"];
  SHKItem *item = [SHKItem URL:url title:@"ShareKit is Awesome!"];
  
  // Get the ShareKit action sheet
  SHKActionSheet *actionSheet = [SHKActionSheet actionSheetForItem:item];
  
  // Display the action sheet
  [actionSheet showFromToolbar:navigationController.toolbar];
  action:@selector(share)]

But still same error

**Comment by gfontenot** [comment]
It's incredibly hard to help you if you don't bother to format your code correctly. But undo what you just did, because you didn't listen to what I was saying.

Your piece of code that looks like this:

```
[[UIBarButtonItem alloc] initWithBarButtonSystemItem:UIBarButtonSystemItemAction
                                      target:self
                                      action:@selector(share)]
```

It needs a semi-colon at the end of it.

This isn't a help forum. Please ask somewhere else if you still have problems.
