### ISSUE TITLE
Twitter button twice crashes app

### ISSUE THREAD

**Issue by leearmstrong** [ideashower/ShareKit#123]
shareKit is integrated and working great in my project at the moment.  I can click the button, show the ActionSheet and send to Twitter.  If I do it a second time it crashes.  BreakPoints show it bombing out on this line...

while (topViewController.modalViewController != nil)

Within the - (UIViewController *)getTopViewController

**Comment by leearmstrong** [comment]
The actionSheet is being presented on a ModalViewController itself.

If you try repeated times on the same Modal View it works.  If the view dismisses and a new view comes up this is where the error occurs.

Facebook and e-mail do not crash, just Twitter!

**Comment by leearmstrong** [comment]
Fixed by setting 

[SHK setRootViewController:self.view];

**Comment by songer522** [comment]
Hi leeus, I got the same problem in my code and I don't quite get your solution, can you be more specific?  Where did you put that line of code? And how can you set rootviewcontroller to a view?

**Comment by yamani** [comment]
where to put this line:
[SHK setRootViewController:self.view];
