### ISSUE TITLE
Instapaper

### ISSUE THREAD

**Issue by CraigMerchant** [ideashower/ShareKit#13]
Add Instapaper

Very simple API details are at http://blog.instapaper.com/post/73123968/read-later-api

**Comment by prime31** [comment]
There are great docs on how to add a service: http://getsharekit.com/add/

Why not take the simple API details and create a patch?

**Comment by ideashower** [comment]
SHKInstapaper has been committed to the master and will appear in the next release.  Thanks to Sean Murphy and Chrissr
