### ISSUE TITLE
Ability to Logout

### ISSUE THREAD

**Issue by ideashower** [ideashower/ShareKit#14]
Need a way to for users to logout of either all or a specific service.  The latter would be the most ideal.

**Comment by ideashower** [comment]
Added in version 0.1.5

**Comment by samjarman** [comment]
How do you do this? and can you do make it a new action on a button eg -(IBAction)logUserOutOfTwitter;

This would let the user be able to tweet/fb etc from diferent accounts

**Comment by ideashower** [comment]
Check out:
http://getsharekit.com/docs/#logout
