### ISSUE TITLE
FEATURE REQUEST: Integrate logout button into SHKShareMenu directly

### ISSUE THREAD

**Issue by coneybeare** [ideashower/ShareKit#141]
Users do not want to have to bounce all over your app to find settings.  It is much more user friendly to contain the logout buttons for the services, or at least the global logout button inside the SHKShareMenu directly.  It can be a red button underneath the Services section, or something similar.

Currently, I implemented a simple action and made it last, but this seems unclean, plus it makes logout show up in the top three after being pressed.

**Comment by leearmstrong** [comment]
Can you share this action with us, I would really like that!

**Comment by coneybeare** [comment]
Normally I would fork it and do a pull request, but ideashower is pretty unresponsive here lately so I will distribute it the old fashioned way.

[Here](http://cloud.coneybeare.net/373u3e1A0v16342S2u0z) is the Logout action. Place it in `/path/to/ShareKit/Sharers/Actions/`

Add an entry for `SHKLogout` to the `SHKSharers.plist` file like so:
![Alt text](http://f.cl.ly/items/200Y2G0y0l3J3315302t/Screen%20shot%202011-03-01%20at%2010.25.20%20AM.png)
