### ISSUE TITLE
Possible bug in [SHKFacebook logout]

### ISSUE THREAD

**Issue by egorFiNE** [ideashower/ShareKit#147]
"+ (void) logout" is a class method, yet it references "self" from the method body: 
        fbSession = [FBSession sessionForApplication:SHKFacebookKey
                                                 secret:SHKFacebookSecret
                                               delegate:self];
Is that correct?

**Comment by MichelleElliott** [comment]
It does not appear to be correct.   Though it is legitimate to reference "self" in a class method, the SHKFacebook class object does not implement the FBSessionDelegate interface -- it is SHKFacebook instances that do so -- and session:didLogin is a required method.  If a session:didLogin: message were ever sent to the SHKFacebook class object, an exception would be raised.
