### ISSUE TITLE
fail to compile

### ISSUE THREAD

**Issue by tzurs** [ideashower/ShareKit#150]
I've pulled the latest and it fails to compile with the following:
SHKEvernoteUserStoreURL, SHKEvernoteNetStoreURLBase

anyone knows what values should be given to these?
thanx.

**Comment by bobbypage** [comment]
Just add the following to SHKConfig.h: 

<pre><code>
// Evernote - http://www.evernote.com/about/developer/api/
#define SHKEvernoteUserStoreURL     @""
#define SHKEvernoteSecretKey        @""
#define SHKEvernoteConsumerKey      @""
#define SHKEvernoteNetStoreURLBase  @""
</code></pre> 

Once you add that it should compile.

Then if you plan to use Evernote in your app, fill in those values with the corresponding API keys which you can get from http://www.evernote.com/about/developer/api/

**Comment by tzurs** [comment]
thanks for the reply, however, how to compile successfully I'm sure most developers would manage, its the "meaning" of each of these constants that is not clear (when you go to the evernote api site you can't find "correct" values for example "EvernoteNetStoreURLBase", It would be helpful if whoever wrote this wonderful extension add a comment on top of each constant to hint what they mean (the secret key and consumer key are intuitive)

**Comment by krzyzanowskim** [comment]
well... this is still valid. Why source simply doesnt compile ouy of the box? I think it should be defined empty by default
