### ISSUE TITLE
issue regarding share menu editing

### ISSUE THREAD

**Issue by mehtaVikram** [ideashower/ShareKit#159]
I am very happy to see that sharekit has removed so much hassle.
But I found an issue. The issue is when you try to edit the share menu and press done, the changes were not saved. I am using iphone4 device and ios 4.2.1.

I found this issue in SHKShareMenu.m

[toggle setOn:!toggle.on animated:YES];

```
    if (toggle.on)
        [exclusions removeObjectForKey:[rowData objectForKey:@"className"]];
           else
        [exclusions setObject:@"1" forKey:[rowData objectForKey:@"className"]];
```

It seems , since you use the animated:YES for the switch, the following code (if toggle.on) is executed before the animation is compete and it samples old value of toggle.on.

Now I changed the  [toggle setOn:!toggle.on animated:NO]; and now it works as expected.

**Comment by mehtaVikram** [comment]
basically the edit menu does not work reliably , you have to switch on/off multiple times to commit changes

**Comment by tgaul** [comment]
There's another way to fix the problem without disabling the animation, which is nice to have. Assign a local variable and use that rather than reading the new "on" value. For example:
    BOOL newOn = !toggle.on;
    [toggle setOn:newOn animated:YES];
    if(newOn)
        ...
