### ISSUE TITLE
Delicious Question (probably not a real bug)

### ISSUE THREAD

**Issue by prime31** [ideashower/ShareKit#16]
The Delicious support is using v2 of the API which is OAuth.  I can't for the life of me find any docs as to what the SHKDeliciousCallbackUrl is used for.  From what I can tell the API setup should have the app as a desktop (not web-based) app.  None of my Delicious calls work whether I use a Yahoo ID or a Delicious login.

Any idea where some relevant docs are (whatever you used when making it would be awesome)?

**Comment by ideashower** [comment]
Couple of things here:
A. The callback is used to intercept the web view.  When the user authorizes the OAuth access inside the webview, ShareKit looks to see when the webview redirects to your callback url.  Once it does this it closes the webview.  In the case of Delicious I don't remember finding a place to set the callback in the YDN site.  I think you can put any url value here and it should work.  The user will never actually see the callback url.

B. In the Yahoo Application Platform did you enable read/write access for Delicious?

**Comment by prime31** [comment]
Read/write is set for Delicious on both of my test API apps.

After some more testing (with both a desktop and web API key/secret) it appears I successfully can get the oauth_verifier and oauth_token with any callback URL as you said.  From there, I can't successfully save to Delicious with either a Delicious login or a Yahoo login.

I get an error of:
<?xml version="1.0" standalone="yes"?>
<result code="no user associated with these credentials" />

Any idea what that could be?  Thanks for your assistance as well.

**Comment by ideashower** [comment]
Is the user a legacy Delicious user account or a new yahoo account?

**Comment by prime31** [comment]
One legacy Delicious account from ages ago and one brand new (1 week old) yahoo account.

**Comment by ideashower** [comment]
Are you still having this problem?

Try the latest (version 0.1.5).  It has a few updates to the delicious sharer and has a new DEBUG mode (see the bottom of SHKConfig) that might help get a few more details about what is happening.

**Comment by prime31** [comment]
Thanks for the update.  I am getting the same error with the latest version:
"No user associated with these credentials"

This happens after successfully logging in and giving permission to the app.  Have you successfully posted to Delicious with old and new style logins?

**Comment by ideashower** [comment]
I've only tested new style logins and those have worked fine.  Maybe try creating a new user to check if it is a problem with the account you are testing?

Have you modified SHKDelicious or any of the OAuth classes?

**Comment by prime31** [comment]
Wow.  Good call on that one.  I just created new Yahoo accounts and everything works now.  Really odd...

Thanks for you assistance on this!

**Comment by robseward** [comment]
I was having the same problem. My delicious account gave me the "No user associated with these credentials" error. A new account works fine though. My old account was created before d was acquired by yahoo; also it's the same one that I created the key with--I wonder what it's problem is.

**Comment by mannby** [comment]
I have an old account, and a brand-new account. The old account gets the error "Please provide valid credentials" and the new account gets the error "no user associated with these credentials". It worked a few times after I set the value of the "realm" parameter to "yahooapis.com", but is now not working again. I'm using version 0.2.1. Any ideas? Should the yahoo project be set up as a client or as a web app?

**Comment by mannby** [comment]
Hmm. The new account now works, after some further activation steps on delicious.com.

**Comment by mannby** [comment]
Hmmm. The old account now claims to work, after making profile changes to the Yahoo/Delicious accounts. However, the bookmarks are not showing up in the account.
