### ISSUE TITLE
SHTwitter -promptAuthorization does not set consumer key

### ISSUE THREAD

**Issue by joshfrench** [ideashower/ShareKit#168]
I'm trying to pre-authorize some services including Twitter. I'm using -promptAuthorization as follows:

```
SHKTwitter *twitter = [[[SHKTwitter alloc] init] autorelease];
[twitter promptAuthorization];
```

When I submit the login form, I receive this error: `Failed to validate oauth signature and token`. Debugging that request, I can see the params include `oauth_consumer_key=(null)`.

When I use the default action sheet to authenticate instead, that parameter is correctly populated with my Twitter app's API key as defined in SHKConfig.h.

**Comment by dlinsin** [comment]
I think you should use the method <code>\- (BOOL)authorize;</code> on <i>SHKSharer</i> instead of <code>\- (void)promptAuthorization;</code>. That should work and takes care of figuring out how to initialize the key/secret.

**Comment by joshfrench** [comment]
`SHKSharer -authorize` just calls `[self promptAuthorization]` and I end up with the same problem. I can see that within `SHKOauthSharer -tokenAccess` the `consumer` instance variable is nil, but I'm not sure where or when that's supposed to be set.

**Comment by dlinsin** [comment]
Well it should call <code>isAuthorized</code> on <i>SHKOAuthSharer</i>, which in turn should call <code>restoreAccessToken</code> and thus initialize consumer with key/secret.

**Comment by joshfrench** [comment]
You're right, `-authorize` does set the consumer key. But it also returns `YES` without then prompting the end user for their own login credentials (see SHKSharer.m#298).

I'm trying to prompt the user to log in to Twitter _before_ they share anything. So it works if I do this:

```
SHKTwitter *twitter = [[[SHKTwitter alloc] init] autorelease];
[twitter authorize];
[twitter promptAuthorization];
```

...which is redundant. Is that really the only way to accomplish this?

**Comment by dlinsin** [comment]
It only returns YES if you have been authorized before, check SHKSharer:

<code>
- (BOOL)authorize {
  if ([self isAuthorized])
      return YES;
  else 
      [self promptAuthorization];
  return NO;
  }
  </code>

otherwise it'll prompt for authorization.

**Comment by joshfrench** [comment]
Looks like it was holding on to the previous (invalid) token -- once I logged out it worked as expected. Thanks for your explanation!

**Comment by nicw** [comment]
I am having this exact issue - and deleting my app and reinstalling isn't solving the issue. Given that I've cleared all data, Sharekit shouldn't think that I'm previously authorized. How can I help troubleshoot this issue? I've set my consumer key and secret in both the default configurator as well as my own.

The error I see is this: OAMutableURLRequest parameters oauth_consumer_key=(null)&oauth_nonce=225853BD-3AAB-47FF-8857-23FDCE470103&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1337733479&oauth_version=1.0
2012-05-22 17:37:59.766 AppName[15419:707] <0xeed7ac0 SHKOAuthSharer.m:(109)> tokenRequestTicket Response Body: Failed to validate oauth signature and token

**Comment by fmundaca** [comment]
i'm having the same issuse.... this is a log from [OAMutableURLRequest _signatureBaseString] 

 param (
    "oauth_consumer_key=(null)",
    "oauth_signature_method=HMAC-SHA1",
    "oauth_timestamp=1381552755",
    "oauth_nonce=DF50EC87-FEF5-4F37-B901-E63AF995B95D",
    "oauth_version=1.0"
)

I need some help please... :)
