### ISSUE TITLE
Display actionSheet from my bar button item causing error.

### ISSUE THREAD

**Issue by heysuburbia** [ideashower/ShareKit#170]
My project in short:
- I added a Toolbar with a bar button item and set its identifier to "action" in Interface builder.
- In my .h I have: "-(IBAction)shareBtn: (id) sender;"
- In my .m (at top) I have: "#import "SHK.h"
- In my .m I have: 
  "-(IBAction)shareBtn: (id) sender{  
  // Create the item to share (in this example, a url)
  NSURL *url = [NSURL URLWithString:@"http://getsharekit.com"];
  SHKItem *item = [SHKItem URL:url title:@"ShareKit is Awesome!"];
  
  // Get the ShareKit action sheet
  SHKActionSheet *actionSheet = [SHKActionSheet actionSheetForItem:item];
  
  // Display the action sheet
  [actionSheet showFromToolbar:navigationController.toolbar];
  }"

I get an error on the last line regarding the navigationController... 
('navigationController' undeclared (first use in this function))

**Comment by dlinsin** [comment]
I'm assuming your shareBtn method is located within a UINavigationController. So why don't you use <i>self.toolbar</i> instead of <i>navigationController.toolbar</i>

**Comment by heysuburbia** [comment]
Thank You.
adding "self" did it, but like this:
[actionSheet showFromToolbar:self.navigationController.toolbar];
