### ISSUE TITLE
Multiple popover when showFromBarButtonItem on iPad

### ISSUE THREAD

**Issue by yasirmturk** [ideashower/ShareKit#182]
Hi, seems like the multiple popover keep on displaying when you use showFromBarButtonItem on iPad and just keep on clicking the Share Button.

**Comment by shrtlist** [comment]
As a workaround, you can make the SHKActionSheet a property and dismiss it prior to displaying a new one, something like:

```
if (actionSheet.visible) {  
    [actionSheet dismissWithClickedButtonIndex:-1 animated:YES];  
}

// Get the ShareKit action sheet
self.actionSheet = [SHKActionSheet actionSheetForItem:item];

// Display the action sheet
[actionSheet showFromBarButtonItem:shareButton animated:YES];
```

**Comment by yasirmturk** [comment]
Yeh did something like that ..at that time :)
