### ISSUE TITLE
Sharekit services are different on simulator?

### ISSUE THREAD

**Issue by ericrsa2004** [ideashower/ShareKit#185]
I did a search and couldn't find it addressed, but the services available on my iDevice are different than the ones available on the iOS simulator.

When my app is launched on the simulator Sharekit offers the full list of services, but when launched on my iDevice the same project only gives me Facebook, Twitter, & Tumblr as options for sharing.

Am I doing something wrong?

Thanks, this framework seems fantastic.

**Comment by alariccole** [comment]
Clear your favorites list.

**Comment by ericrsa2004** [comment]
Thanks,

I discovered "Clean all targets" works too.
