### ISSUE TITLE
Twitter reporting "invalid application"

### ISSUE THREAD

**Issue by yabdab** [ideashower/ShareKit#188]
I have triple checked my settings on the twitter.com/apps web site and within my SHKConfig file and I keep getting the "invalid application" error.

<0x5d53cb0 SHKTwitter.m:(356)> Twitter Send Status Error: {"request":"\/1\/statuses\/update.json","error":"Invalid application"}

Does it take some time before Twitter allows a new app to start working?  

Anyone else experience this issue?

**Comment by sykte** [comment]
nope, it's instant. Copy and Paste your settings into the config

**Comment by yabdab** [comment]
Oh well, everything is set up correctly and the error message is vague. Will try the xAuth route instead.
