### ISSUE TITLE
FBXMLHandler doesn't compile with SDK 3.2

### ISSUE THREAD

**Issue by dginsburg** [ideashower/ShareKit#19]
NSXMLParserDelegate didn't formally exist prior to iOS 4.0.

**Comment by ideashower** [comment]
I'd recommend building with the Base SDK set as 4.0 and then setting your iPhone OS Deployment Target lower at 3.2 (or lower).

**Comment by sindresorhus** [comment]
Still errors. This fixed it for me though:

<pre><code>
#ifdef __IPHONE_4_0
    @interface FBXMLHandler : NSObject &lt;NSXMLParserDelegate&gt;
#else
    @interface FBXMLHandler : NSObject
#endif
{
</code></pre>
