### ISSUE TITLE
No modal form for second sharing attempt after cancelling first

### ISSUE THREAD

**Issue by dginsburg** [ideashower/ShareKit#20]
See comment.

**Comment by dginsburg** [comment]
I have more information. Rather silly of me to blame it on a specific URL.

The problem is the second URL I attempt to share after canceling the first share. It gets into SHK showViewController. currentView is non nil so it calls a dismiss and returns. The comment implies it will make another attempt to display but it doesn't.

**Comment by dginsburg** [comment]
I believe this bug is because of the SHK *currentHelper singleton, specifically the rootViewController property. I'm invoking ShareKit from within a modal. So the first time through the root is being stored. The next time I use ShareKit I'm within a new modal but the old root has been stored and is being used to present ShareKit.

**Comment by dginsburg** [comment]
Rather than trying to figure out the top level view controller I'd prefer if you let me specify. Then you don't need what looks to me to be a somewhat fragile process of trying to determine the right controller at the right time. And with a SplitViewController based UI I may want control over this.

**Comment by ideashower** [comment]
You can set the root view manually.  See the common issues section here: http://getsharekit.com/support/#issues

I'll look at having it automatically update as well.

**Comment by ideashower** [comment]
Had a brain fart with my last comment.

SHK will always present on the top view controller from your root view controller stack.  Before displaying the view it calls getTopViewController which starts at your rootViewController and jumps up through any modal views.  This way the view is displayed on top of the highest modal view controller.

It sounds like you may have done something to stop calling viewWasDismissed on SHK after the modal goes away.  When a SHKFormController disappears (see viewDidDisappear) it calls [[SHK currentHelper] viewWasDismissed].  This tells SHK to open any pending views.

**Comment by dginsburg** [comment]
The problem is that rootViewController which was stored is no longer hooked up to anything. It was a modal that I've dismissed and released. The only reason it still exists is because SHK has retained it.

**Comment by dginsburg** [comment]
I am setting the property manually now and it works. But to get to that point took a lot of debugging and learning how the library managed it's views. You need more than a note in the common issues area to address the design not working in this scenario. I think the fact that the user may need to override the behavior without knowing when or why is an indicator that it needs to be rethought.
