### ISSUE TITLE
Facebook iOS lib is too old

### ISSUE THREAD

**Issue by ghost** [ideashower/ShareKit#204]
There is no "Facebook" object implementation and it really bugs up when app is using facebook ios sdk for authentication purposes (having one before sharekit was added to the app). Leaving one or the other sdk - breaks opposite feature's functionality:
- when using own/new facebook sdk - there is no "FBSession" which makes sharekit not compile.
- when using sharekit's facebook sdk - there is no "Facebook" which makes whole app not to compile.

Please fix this ASAP.

**Comment by spidaman** [comment]
Have you looked at this fork? https://github.com/colinhumber/ShareKit - seems to work fine (though the JSON library is outdated and incompatible with the newer ones, sigh)

**Comment by ghost** [comment]
Thanks for the tip. So it fixes one problem, but introduces the other?

**Comment by spidaman** [comment]
It only introduces a problem if you're using a newer version of the JSON library than the one that FBConnect uses. However, removing the version of the JSON library that is distributed with FBConnect and patching FBConnect to use the newer JSON API (which we already use in our app) was easy.

**Comment by ghost** [comment]
Sigh... Thanks for the headsup. Guess it's far from drop-in replacement. Will look into it further.
