### ISSUE TITLE
Facebook doesn't work anymore

### ISSUE THREAD

**Issue by adamawolf** [ideashower/ShareKit#207]
This is in an already published application that was previously working.

The popup appears. If the user is not logged into Facebook, the login pages appears correctly.

After logging in the blue title bar goes blank. The web view goes blank white. Expected behavior: the publish page is loaded in the web view inside of the Facebook popup.

Pressing the X button dismisses the Facebook popup. Subsequent Facebook sharing attempts bring up the Facebook popup but it is again blank. Expected behavior: the publish page is loaded in the web view inside of the Facebook popup.

It sounds like some responders to Issue 206 are having this same problem, but Issue 206 is not the same as this as this does not relate to timing out. This is in a fresh install of the application.

**Comment by mediabounds** [comment]
I'm experiencing a similar issue. As of today, any attempt to use Facebook to share ends up with a Page Not Found error.

**Comment by ideashower** [comment]
Just tested and confirmed.

Looks like they either broke or dropped support for the Facebook Connect SDK Library that ShareKit uses.  

We'll probably need to move to the new Facebook Graph API instead.

**Comment by mediabounds** [comment]
There's a pull request that updates ShareKit to the Facebook Graph API. There's no dialog box pop up anymore (just shares is set in the code), but it does work!
https://github.com/ideashower/ShareKit/pull/158

**Comment by ideashower** [comment]
Awesome, I'll test that out.

Been meaning to get a big update to ShareKit out soon, might be the final straw!

**Comment by pocketpixels** [comment]
I've filed a bug with Facebook on the issue: 
http://bugs.developers.facebook.net/show_bug.cgi?id=16766
Please vote it up and/or comment on it.

**Comment by gdawg** [comment]
Similar failures for me with a few different apps. Will vote up teh facebook bug.

**Comment by taberrr** [comment]
Yeah it's pretty much the same issue I'm seeing (#206). Bummer.

**Comment by brunobr** [comment]
Having problems with this issue in various apps for iPhone but the iPad apps are still working, even the ones that are "universal" and use the same methods wont work for iPhone and work for iPad... maybe a user agent problem?

**Comment by mediapunk** [comment]
I voted up the facebook bug, but I'm wondering... what's the best bet for a quick fix to this? Should I use pull request 158?

**Comment by ckweb** [comment]
I voted up the bug too. Thanks for filing it, pocketpixels.

**Comment by mediabounds** [comment]
Pull request #158 works for me for now. I liked that previously, it would pop up a dialog and let the user see what was being posted on the wall. Unfortunately, pull request #158 just posts automatically (doesn't matter how you have the "post automatically" flag set).

**Comment by coneybeare** [comment]
@ideashower +1 "Been meaning to get a big update to ShareKit out soon, might be the final straw!" There are many pull requests already… might not be too hard.

**Comment by taberrr** [comment]
Using https://github.com/ideashower/ShareKit/pull/158 I was able to fix this issue (I think! Gonna try sharing again tonight/tomorrow to see if the auth component still works, re #206). If you want to customize your share, similar to the "old" wall post dialogue take a look at: http://developers.facebook.com/docs/reference/dialogs/feed/ and call `[self.facebook dialog:@"feed" andParams:params andDelegate:self];` in your SHKFacebook's `-(void) share` method.

**Comment by brunobr** [comment]
It was a Facebook-side error and was already fixed, please close the issue. Thanks!

**Comment by adamawolf** [comment]
Confirmed that the issue is resolved in my published app that was exhibiting this problem. Closing.

**Comment by 1root** [comment]
This issue just started happening today for me. Did this problem re-appear?

**Comment by steprazor** [comment]
Happening for me too! A little different than the last time. Hopefully this is a facebook side issue again.

**Comment by 1root** [comment]
Here's the fix: ---> https://github.com/ideashower/ShareKit/issues/234

**Comment by steprazor** [comment]
Thanks
