### ISSUE TITLE
Unable to post to Twitter - "Invalid Application"

### ISSUE THREAD

**Issue by catbus** [ideashower/ShareKit#217]
All other services work wonderfully, but I'm unable to successfully post to Twitter using OAuth.

I've followed the instructions in SHKConfig.h to the letter.   Tried regenerating keys and completely deleting and recreating the app on Twitter's dev site many times.  Same results each time:

<0x35d8cb0 SHKTwitter.m:(356)> Twitter Send Status Error: {"request":"\/1\/statuses\/update.json","error":"Invalid application"}

Would be awesome if someone has a solution for this.  Thanks!

**Comment by yabdab** [comment]
I had same problem. In a previous test of my app, Sharekit saved the twitter login I used somewhere is User Defaults. 
I had to specifically tell my app to logout of twitter. Then after that, the twitter service functioned as normal.

**Comment by catbus** [comment]
Ah, thank you!  Great tip.

To resolve it did you have to trigger the twitter logout each time the app ran or just once to purge the data from User Defaults?

**Comment by yabdab** [comment]
I did it the one time to clear out incorrect login data. It has worked fine since then. I suppose you could add a button that would allow user to logout manually, but would require some custom coding to add it in.

**Comment by catbus** [comment]
Yep, just confirmed - a single call to:

[SHK logoutOfService: @"SHKTwitter"]; 

does the trick.  Thanks for pointing me in the right direction.
