### ISSUE TITLE
Provide a constant for a known invalid/cancel button index

### ISSUE THREAD

**Issue by dginsburg** [ideashower/ShareKit#22]
It may be necessary to dismiss the UIActionSheet with dismissWithClickedButtonIndex:animated:. For an iPad app you do it to avoid having multiple popovers. For an iOS4 app you may want to dismiss when the app moves to the background. It would be nice to have a known constant for a button index that won't get interpreted as an action.

**Comment by ideashower** [comment]
Using index -1 I believe is the standard for UIActionSheet on cancel.  However I see a bug in the SHKActionSheet that would still handle indexes below 0.  I will fix that.

**Comment by ideashower** [comment]
Fixed in version 0.1.5
