### ISSUE TITLE
Facebooks Like Button...possible?

### ISSUE THREAD

**Issue by lexar** [ideashower/ShareKit#228]
Hi, 
is it possible to use Facebook's "Like"-Button with ShareKit?

Thank you, x

**Comment by lexar** [comment]
Please..anyone? A simple "Yes" would do :)

**Comment by gdawg** [comment]
I've looked into this briefly and suffice it to say that with the current api it's not going to be _easy_ to do. 

There doesn't seem to be any official support for doing general Like support unless you're using the web api.

**Comment by lexar** [comment]
Pity, but thanks anyway!

**Comment by ay8s** [comment]
If you have a Facebook Session available it is possible to display a Like Button within a UIWebView that is being served from a HTML file within the app itself. Done this recently and it worked correctly. I can dig out code if you like.

**Comment by gdawg** [comment]
I haven't looked at doing this in ages but I'd love to see the code if you've got it handy! 

Is there any need to do magic cookie work with the webview or does it all "just work"??

**Comment by ay8s** [comment]
I'll try and dig it out.

As long as you have a Facebook session within the app/view that is logged in displaying a like button from a HTML file that is within the app within a UIWebView works. You can also get callbacks as you normally would if you were doing a Facebook tab etc.
