### ISSUE TITLE
Incorrect Signature - Twitter error

### ISSUE THREAD

**Issue by jayrparro** [ideashower/ShareKit#229]
I'm using ShareKit in my app to integrate FB & Twitter status updates.
The FB service is working fine. However, in my Twitter service I encountered this error:
    Twitter Send Status Error: {"request":"\/1\/statuses\/update.json","error":"Incorrect signature"}

This happen to me on 1-3rd try but when I try to run/debug again the app, it will update successfully.

So, I don't know what's really the problem.

The consumer & secret keys are all correct.

**Comment by bash3r** [comment]
You need to change SHKTwitter.m in lines 54-56 from https://twitter.com/ to https://api.twitter.com/

`self.authorizeURL = [NSURL URLWithString:@"https://api.twitter.com/oauth/authorize"];
self.requestURL = [NSURL URLWithString:@"https://api.twitter.com/oauth/request_token"];
self.accessURL = [NSURL URLWithString:@"https://api.twitter.com/oauth/access_token"];`

**Comment by jdelStrother** [comment]
I've seen a few users running into this problem in our app, but never been able to reproduce it myself.  bash3r - what makes you think that the domain name causes this issue?

**Comment by bash3r** [comment]
1. It solved the problem for me.
2. Line from Twitter oAuth docs: Use api.twitter.com - for all your OAuth steps, use api.twitter.com as the hostname, not just "twitter.com"

**Comment by jdelStrother** [comment]
Hmm, fair enough.  Were you persistently seeing the problem, or did it come and go?

**Comment by bash3r** [comment]
8 out of 10 requests failed due to invalid signature ...

**Comment by jdelStrother** [comment]
Hmm, odd.  What I'm seeing only seems to affect a tiny percentage of users.  I'll try updating the hostname anyway and see if it helps.

**Comment by jayrparro** [comment]
bash3r, you're right. Twitter oAuth docs is updated likewise we should update ShareKit to fix this issue. Can you send the pull request for this to fix it in next version?

Btw, in addition for the fix..should update the sendStatus method to use https 

<pre><code>
    OAMutableURLRequest *oRequest = [[OAMutableURLRequest alloc] initWithURL:[NSURL URLWithString:@"https://api.twitter.com/1/statuses/update.json"]
                                                                    consumer:consumer
                                                                       token:accessToken
                                                                       realm:nil
                                                           signatureProvider:nil];
</code></pre>

Excerpts from docs: "Please use HTTPS for this method, and all other OAuth token negotiation steps."
https://dev.twitter.com/doc/get/oauth/authorize
