### ISSUE TITLE
Authorization doesn't works in iOS 5

### ISSUE THREAD

**Issue by soniccat** [ideashower/ShareKit#247]
When I call [SHKTwitter authorize:self]; or call the authorize method for any other SHKOAuthSharer subclass I have infinity loading hud with "Connecting..." title. Now I am trying resolve that issue. I see that in OAAsynchronousDataFetcher.m file in start method that code:

connection = [[NSURLConnection alloc] initWithRequest:request delegate:self];

It works, but I can't catch any delegate's calls. Nothing from that was called:
- (void)connection:(NSURLConnection *)aConnection didReceiveResponse:(NSURLResponse *)aResponse;
- (void)connection:(NSURLConnection *)aConnection didReceiveData:(NSData *)data;
- (void)connection:(NSURLConnection *)aConnection didFailWithError:(NSError *)error;
- (void)connectionDidFinishLoading:(NSURLConnection *)aConnection;

So strange, I don't understand why. Need your help.

**Comment by tnbeatty** [comment]
If you look at the documentation, most of the NSURLConnectionDelegate protocol is only available through iOS 4.3 and has been superseded/unsupported in iOS 5.

**Comment by jspoto** [comment]
Is there any information on the new classes/methods to be used instead?

Also, should work begin on a simple iOS 5 "port" of the mainline?

**Comment by soniccat** [comment]
Seems that was an Internet security problem in our company, sorry.
