### ISSUE TITLE
Norwegian translation Localizable.strings

### ISSUE THREAD

**Issue by danielkaldheim** [ideashower/ShareKit#252]
Hello,
I was not quite sure where I would add this.
But I missed the Norwegian translation, so I translated it and thought others could benefit from this.

Here is my translation: (UTF8)
http://kaldheim.org/library/filer/zip/nb.lproj.zip

**Comment by sindresorhus** [comment]
You should look through the pull requests before submitting. 
This already exists: https://github.com/ideashower/ShareKit/pull/133
