### ISSUE TITLE
How to make FBconnect modal?

### ISSUE THREAD

**Issue by darbien** [ideashower/ShareKit#256]
For my app, it looks like the facebook menu that is popped up is not modal. When the facebook menu is on the screen the user can also select other game elements. This isn't a big problem on the iphone since the facebook menu is almost cover the entire screen, but for ipad is a bigger issue. I would like to make it so when the facebook menu is active all the background greyed out and disabled.  

Is there a easy way to achieve this? Perhaps I will have to modify FBDialog class?

It looks like the twitter module works fine without this problem.  I'm not sure why FBConnect have this problem.

**Comment by JustinKent** [comment]
Running into the same issue. Any progress on a fix or workaround?

**Comment by JustinKent** [comment]
I fixed this by adding the following code to FBDialog.m:

```
- (UIView *)hitTest:(CGPoint)point withEvent:(UIEvent *)event {
    if ([self pointInside:point withEvent:event] == YES) 
    {
        return [super hitTest:point withEvent:event];
    }
    else
    {
        return self;
    }    
}
```

**Comment by darbien** [comment]
Cool thanks Justin, will give it a try!
