### ISSUE TITLE
Sending String to facebook is not working

### ISSUE THREAD

**Issue by lucagianneschi** [ideashower/ShareKit#261]
When I'm sendining NSString to Facebook, to write it down on  the wall, it's not working, the App doesn't show up m string, but "enter your message". Few days ago everything was fine. Has something changed? Any Solution?

**Comment by vargonian** [comment]
I'm having this exact same problem; it's really bad timing because it worked the day that I submitted the app, and the app hit the store today and it doesn't.  It doesn't work from the simulator, etc. anymore either.

**Comment by naja1987** [comment]
I'm having the same problem, too. Has Facebook changed something in their APIs??

**Comment by lucagianneschi** [comment]
maybe Yes, cause I check yesterday and today some other App usig Share Kit and the seems to be affected qith the same issue... hope someone is going to say what to do... I sincerely don't know where to find the issue in the code... and I think the problem persist if I change framework for sharing, cause if FB changed the APIs those are used also for other frameworks..

**Comment by heuristicmedia** [comment]
I have the same problem with the current stable version of ShareKit. This fork that uses FBConnect for authentication is working for me.

https://github.com/dagerydoo/ShareKit

**Comment by lucagianneschi** [comment]
Did you solve with this?
#import "SHKFacebook.h"
1. In your AppDelegate, include these two methods (or merge if you already use them, remembering to properly delegate):
- (BOOL)application:(UIApplication *)application 
          openURL:(NSURL *)url 
  sourceApplication:(NSString *)sourceApplication 
         annotation:(id)annotation 
  {
  return [SHKFacebook handleOpenURL:url];
  }
- (BOOL)application:(UIApplication *)application 
    handleOpenURL:(NSURL *)url 
  {
  return [SHKFacebook handleOpenURL:url];
  }
1. In your App-Info.plist, include this property:
   
   ```
   <key>CFBundleURLTypes</key>
   <array>
           <dict>
                   <key>CFBundleURLName</key>
                   <string></string>
                   <key>CFBundleURLSchemes</key>
                   <array>
                           <string>fb${FACEBOOK_APP_ID}</string>
                   </array>
           </dict>
   </array>
   ```

Where fb${FACEBOOK_APP_ID} looks like fb1234
1. Finally, in SHKConfig.h, set the facebook API ID:

#define SHKFacebookAppID      @"1234"
1. Follow the standard ShareKit instructions below

**Comment by heuristicmedia** [comment]
This fork uses a different authentication workflow for Facebook, and the code posted above is required to support it. Maybe FB changed or deprecated something in their old API that caused ShareKit to fail.

**Comment by lucagianneschi** [comment]
I'm gonna try it... does it work for the simulator too??
This issue was really unpleasent, cause I relesed 4 new versions of my Apps introducing ShareKit and it worked just for 1 day.. I'll let you now it it did the trick. Thanks

**Comment by dagerydoo** [comment]
@heuristicmedia — In late May, FB (at least) briefly stopped supporting the old authentication mechanism, which ShareKit currently links against (using a circa 2009 FBConnect framework). There are reports that it is now working again, and some find it preferable to the currently supported (and, I would argue, more trustworthy) authentication mechanism (introduced in the 2010 FBConnect framework).

The tradeoff is that the new authentication module will cause your app to swap to either Safari or the Facebook app to present the user with a screen that enables them to **allow** your app certain privileges (post and offline access). Following this, FB opens a url that looks something like fb1234://..., which, by setting the correct value in CFBundleURLSchemes, causes iOS to redirect to your app, where the "..." in the link above will contain an **access token** that you may use to post to the user's wall.

The trick is that you (may) need to restore the user's current state when the app opens back up.

All of that said, I do believe that at some point in the future, FB will pull the plug — permanently — on the old authentication system.

**Comment by heuristicmedia** [comment]
@dagerydoo - I definitely prefer the old auth flow from a UX standpoint, but posting via FBConnect seems far more reliable. Thanks for updating ShareKit to use it.

Now if only Evernote would stop returning 404 errors from the sandbox... ;-)

**Comment by lucagianneschi** [comment]
Sorry, but I didn't get what the solution is... 
@dagerydoo how do you solve? sorry but I'm a newbie of ShareKit...

**Comment by heuristicmedia** [comment]
@lucagianneschi Make sure you're using @dagerydoo's fork of ShareKit (not the version available from http://getsharekit.com) and follow the directions you posted above. This version seems to be much more reliable.

**Comment by lucagianneschi** [comment]
It's sounds a little bit strange... I haven't already done anything... but know all applications running ShareKit (non modified version), are actually working fine......

**Comment by SlavaBushtruk** [comment]
Changed nothing during the week. Today my app was released and it does NOT work. Waiting.. :)
@dagerydoo's fork gives the same result.

Any ideas?
