### ISSUE TITLE
can't send tweets on first app launch (New twitter api issue!)

### ISSUE THREAD

**Issue by mureev** [ideashower/ShareKit#269]
i can't send tweets on fist app launch. 

Twitter response with: {"error":"Could not authenticate with OAuth.","request":"\/1\/statuses\/update.json"}
After that sendDidFailShouldRelogin called. and user again enter login/pass, again send tweet and again Twitter response with this error.

If I close my app and relaunch - all works fine!

**Comment by mureev** [comment]
I compared the successful and unsuccessful request.

oauth_signature, oauth_timestamp and oauth_nonce are diffrent. but it's ok.
trying to find the cause of the problem...

**Comment by mureev** [comment]
aConsumer and aToken (key/secret) are the same in both cases

**Comment by mureev** [comment]
fix this like in here
https://github.com/ideashower/ShareKit/issues/229

You need to change SHKTwitter.m in lines 54-56 from https://twitter.com/ to https://api.twitter.com/

self.authorizeURL = [NSURL URLWithString:@"https://api.twitter.com/oauth/authorize"];
self.requestURL = [NSURL URLWithString:@"https://api.twitter.com/oauth/request_token"];
self.accessURL = [NSURL URLWithString:@"https://api.twitter.com/oauth/access_token"];

and in line 323

 OAMutableURLRequest *oRequest = [[OAMutableURLRequest alloc] initWithURL:[NSURL URLWithString:@"https://api.twitter.com/1/statuses/update.json"]
                                                                    consumer:consumer
                                                                       token:accessToken
                                                                       realm:nil
                                                           signatureProvider:nil];

**Comment by jspoto** [comment]
Is there a pull request with these fixes, based on the current /ideashower repository?
