### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by Ricardo1980** [ideashower/ShareKit#295]
Hello!

It seems to me this project is dead,am I right?

Thanks.

**Comment by burtlo** [comment]
@Ricardo1980 open the 'Network' and you can see various other forks that are sill being maintained. Though, I'll admit it's hard to tell if one of those is the definitive fork to work from ...

**Comment by Ricardo1980** [comment]
I see that, but it seems a bit chaotic, each one with his own fork. Anyway, what about the original author? is he still working in this project? Otherwise maybe the community should create its own fork (instead of hundreds of forks)
Evidently, the community is very interested in this project and there are many people who want contribute, but the main author seems disappear.
What do you think?
Thanks.

**Comment by scompt** [comment]
@Ricardo1980 There's talk of this over at #283. Basically, we all agree with you, we just need to get in motion.

**Comment by Ricardo1980** [comment]
OK scompt, then I close this issue.
