### ISSUE TITLE
Cancel button doesn't work in iOS 5

### ISSUE THREAD

**Issue by newacct** [ideashower/ShareKit#308]
The Cancel button in the share menu and in the authentication dialog don't work in iOS 5 (at least in the simulator)

Steps to Reproduce 1st problem
- Run the Sample app in the iPhone 5.0 simulator
- Choose any of the types to share
- Tap the share button to bring up the action sheet
- Tap more to bring up the menu
- Tap Cancel. Nothing happens

Steps to Reproduce 2nd problem
- Set up the API keys
- Run the Sample app in the iPhone 5.0 simulator
- Choose any of the types to share
- Tap the share button to bring up the action sheet
- Choose Twitter (for example) to bring up the authentication dialog (assuming it was not previously saved)
- Tap Cancel. Nothing happens

**Comment by oadash** [comment]
It's solved here https://github.com/ideashower/ShareKit/issues/254
