### ISSUE TITLE
xAuth iPad Twitter Convoluted bug

### ISSUE THREAD

**Issue by nathanspector** [ideashower/ShareKit#31]
When you first start and do not have an account setup and it is configured for xAuth and you are on an iPad. Open Sharekit. Click More. Click Twitter. That screen no matter how you work it will never go away.  Logging in and hitting cancel does not work.

edit: same thing goes for emailing as well. and tumblr... basically any view controller (not facebook, because thats custom) presented on the ipad after viewing the menu...

**Comment by ideashower** [comment]
Hey Nathan,

By 'not have an account setup' do you mean a developer account that you configured in SHKConfig.m or just a user account?

One other thing to check out is this issue:
http://github.com/ideashower/ShareKit/issues#issue/24

A workaround is posted in there too.  I haven't committed a change for it yet.

**Comment by nathanspector** [comment]
user account

**Comment by ideashower** [comment]
Can you check the other issue I posted and see if that solves it for you?

**Comment by nathanspector** [comment]
worked! thanks man... I've got a couple additions I've gotta send to you as well. how should i do that?

**Comment by ideashower** [comment]
Create a fork, commit your changes to the fork and then shoot me an email (or pull request) with some details.  

That way I can just easily merge.
