### ISSUE TITLE
Share text to twitter

### ISSUE THREAD

**Issue by Ru553ll** [ideashower/ShareKit#32]
When trying to share text with twitter, it will always fail unless I manually type other text into the textview presented. Any idea why that might be? I can type anything as long as it's not just a space and it will work, otherwise it always fails.

**Comment by ideashower** [comment]
Can you turn debug on and see what Twitter is responding with in the console?

Instructions on debug: http://getsharekit.com/support/#issues

**Comment by Ru553ll** [comment]
It says "wait_fences: failed to receive reply: 10004003"

**Comment by Ru553ll** [comment]
I tried it some more and it doesn't give that error again. I'm not seeing any response from twitter logged whether it succeeds or not. all I get is:

<0x7b47990 OAMutableURLRequest.m:(227)> OAMutableURLRequest parameters oauth_consumer_key=MYKEY&oauth_nonce=OTHERDATA&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1279583709&oauth_token=THETOKENj&oauth_version=1.0&status=Each%20day%2C%20compel%20yourself%20to%20do%20something%20you%20would%20rather%20not%20do.

The status is what it should be, but it doesn't post unless I add additional characters (not a space though)

**Comment by Ru553ll** [comment]
If I set a breakpiont in SHKTwitter.m on the method
- (void)sendStatusTicket:(OAServiceTicket *)ticket didFinishWithData:(NSData *)data

I can see that ticket.didSucceed = NO.

When inspecting the data I don't see much, if I drill down to name I see \x1f, though it says it's 70 bytes

when inspecting ticket I don't see much either but under response I can find a "name" which has value \x0f

**Comment by Ru553ll** [comment]
When I add characters to the tweet I see that ticket.didSucceed is then YES, though the name under NSURLResponse is also \x0f. The data item also has name = \x1f, though it is now 1291 bytes.

**Comment by Ru553ll** [comment]
It seems to be an issue with trying to tweet the same text over and over - does twitter not allow this? That would be fine for my application, but it'd be nice to have that as an error message.

If this is the case, I'm willing to contribute that code, but can someone point me to where the exact conditions are documented by twiiter?

**Comment by ideashower** [comment]
Twitter prevents a duplicate message from being tweeted.  Check out their post status api for more.
