### ISSUE TITLE
Using with ARC

### ISSUE THREAD

**Issue by kastony** [ideashower/ShareKit#324]
Setting compiler flags to   -fno-objc-arc gives me 3 errors and 20 warnings. Have anyone implement the sharekit with ARC ?

Thanks in advance

**Comment by Javoid** [comment]
I've got it working despite the warnings, but it sketchy at best.  The cancel button doesn't work on the SHKShareMenu and Facebook photos only post on some of the devices tested.  Addthis is an alternative, but not much better.  Their library has also fallen behind like it's been abandoned as well.

**Comment by Javoid** [comment]
Try https://github.com/ShareKit/ShareKit
