### ISSUE TITLE
share text to facebook

### ISSUE THREAD

**Issue by thomasmckay** [ideashower/ShareKit#33]
Facebook currently supports URL and Image. The 'description' parameter would allow sharing of text as well, if I'm not mistaken.

The SHKItem.text could also be passed along with the URL and Image types. This would allow apps to prepopulate the FB dialog with text from the app.

**Comment by thomasmckay** [comment]
Version 0.1.6

**Comment by ideashower** [comment]
I thought a version fork/commit added this, but I could be wrong.  I'll check it out.

**Comment by dejo** [comment]
This issue is closed now? What was the resolution?

**Comment by ideashower** [comment]
Dupe issue:
http://github.com/ideashower/ShareKit/issues#issue/36
