### ISSUE TITLE
twitter send image on ios5, "there was an error while sharing"

### ISSUE THREAD

**Issue by KarlYu** [ideashower/ShareKit#333]
Hi,

When sending a image after twitter's authorization, it keep say "there was an error while sharing", I have opened the sharekit debug log, but nothing was shown.

Anyone encountered this problem?

**Comment by ghost** [comment]
Hi,

I got the same error please help me, your reply will be appreciated.

Thanks in advance.

**Comment by KarlYu** [comment]
don't see this problem after using, Sharekit2.0.
