### ISSUE TITLE
Offline Instapaper crashes

### ISSUE THREAD

**Issue by andrewstephenson-v1** [ideashower/ShareKit#34]
**\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFDictionary setObject:forKey:]: attempt to insert nil value (key: custom)'

in SHK.m: + (BOOL)addToOfflineQueue:(SHKItem *)item forSharer:(NSString *)sharerId

**Comment by ideashower** [comment]
I'll check this out, thanks

**Comment by ideashower** [comment]
Found the issue, it'll be fixed in the next version (which will be pushed out today or tomorrow).
