### ISSUE TITLE
Twitter Send Status Error: 403 Forbidden

### ISSUE THREAD

**Issue by atash55** [ideashower/ShareKit#348]
Hey

I am Using Sharekit to share my games high score on twitter. I am using cocos2d for the game. I was successfully able to enter my log in credentials and the url was also shortened.But when i send the tweet i am getting this error

<0x853ffa0 SHKTwitter.m:(356)> Twitter Send Status Error: 403 Forbidden: The server understood the request, but is refusing to fulfill it.

Below is the code for the posting part.

-(void)shareOnTwitter 
{

```
NSURL *gameUrl=[NSURL URLWithString:@"http://itunes.apple.com/us/app/the-little-plane-first-journey/id492889909?ls=1&mt=8"];

SHKItem *twitterItem = [SHKItem URL:gameUrl title:@"THE LITTLE PLANE IS AWESOME"];
[SHKTwitter shareItem:twitterItem];
```

}

Can you let me know what the problem is?

Thank you
Atash Qasim

atash@pixelsutra.com

**Comment by atash55** [comment]
<0x853ffa0 SHKTwitter.m:(356)> Twitter Send Status Error: 403 Forbidden: The server understood the request, but is refusing to fulfill it.

**Comment by qburst-krishnachandra** [comment]
I had fixed this. Please refer : http://jayrparro.posterous.com/incorrect-signature-sharekittwitter-error
