### ISSUE TITLE
xAuth Twitter

### ISSUE THREAD

**Issue by nathanspector** [ideashower/ShareKit#35]
Logout? It doesn't exist. This is bad. very bad.

**Comment by ideashower** [comment]
Huh?

Do you mean a way to logout of a service?

http://getsharekit.com/docs/#logout

**Comment by nathanspector** [comment]
yes. i think i may not have 0.16? would that be right?

**Comment by nathanspector** [comment]
I meant it does not exist for the user to see... Which is really bad.

**Comment by ideashower** [comment]
This is left up to the developer to integrate as they choose.  The most common way is simply adding a logout button/option to the app's settings page.
