### ISSUE TITLE
Custom message content

### ISSUE THREAD

**Issue by alariccole** [ideashower/ShareKit#36]
The ability to add an HTML text section for content would be helpful for types such as images which can be emailed. The ability to add text content to the email would help, as well as adding a link to the image or its content. 

This would help with email or Facebooking images, allowing a link or other comments to be added with the image, especially for plugging the iPhone/iPad app or linking to iTunes.

**Comment by ideashower** [comment]
Hey Akaru,

SHKItem has a 'text' property.  This property is used when sending emails and support HTML.  I'll look into the Facebook sharing but I believe this should work as is too.

**Comment by alariccole** [comment]
Thanks. However, adding a text attribute to an "image" item does not seem to add content to an email or a Facebook post as of yet.

SHKItem *item = [SHKItem image:imageView.image title:tit2];
item.text = @"some text";
SHKActionSheet *shkActionSheet = [SHKActionSheet actionSheetForItem:item];
[shkActionSheet showFromRect:CGRectMake(583, 0, 50, 50) inView:self.view animated:TRUE];

**Comment by ideashower** [comment]
K, I'll get this updated in the next version thanks!

**Comment by ideashower** [comment]
This now works for emails and for text/links on Facebook with the latest branch from github.  Still working on using the text property with sharing images to Facebook.

**Comment by ideashower** [comment]
Hey Akaru

Can you post an example of how you'd use the text property with sharing on Facebook that is different then the current method using title?

Setting the SHKItem's title sets the caption used on Facebook.
