### ISSUE TITLE
twitter tokenAuthorize error

### ISSUE THREAD

**Issue by mclark4386** [ideashower/ShareKit#366]
I get the following error from twitter in the webview when I try to use [twitter tokenAuthorize]:
Whoa there! The request token for this page is invalid. It may have already been used, or expired because it is too old. Please go back to the site or application that sent you here and try again; it was probably just a mistake.

I have the twitterConsumerKey, twitterSecret and twitterCallbackUrl are all set the same as on twitter.

**Comment by mclark4386** [comment]
tried [twitter promptAuthorization] as well, same results.

**Comment by mclark4386** [comment]
here is the code:
SHKTwitter\* twit = [[SHKTwitter alloc] init];
    if(![twit isAuthorized]){
        [twit promptAuthorization];
    }
    else {
        UIAlertView\* alert = [[UIAlertView alloc] initWithTitle:@"Oops" message:@"You already have a twitter account bound! Would you like to use this account or logout of it and into another?" delegate:self cancelButtonTitle:@"Use this one!" otherButtonTitles:@"Logout of this one!", nil];
        alert.tag = 1234;
        [alert show];
    }

**Comment by mclark4386** [comment]
fixed in ShareKit/ShareKit

**Comment by bobbypage** [comment]
BTW, the reason for this error is due to not using https when posting a status update the twitter. The problem is in SHKTwitter.m at line 323, where the status is posted using http rather than https:

```
OAMutableURLRequest *oRequest = [[OAMutableURLRequest alloc] initWithURL:[NSURL URLWithString:@"http://api.twitter.com/1/statuses/update.json"]
```

The fix is simple, just change the url to https:

```
OAMutableURLRequest *oRequest = [[OAMutableURLRequest alloc] initWithURL:[NSURL URLWithString:@"https://api.twitter.com/1/statuses/update.json"]
```

**Comment by mclark4386** [comment]
makes sense and good to know^^
