### ISSUE TITLE
Taping send on emails does not dismiss the view - but still sends emails

### ISSUE THREAD

**Issue by samjarman** [ideashower/ShareKit#41]
Tried sending some text in an email.... 'Send' did not close the emails.. but seconds later I heard the sent email woosh.

**Comment by ideashower** [comment]
Sounds like something funky is happening with ShareKit interacting with your views.

How are you launching ShareKit within your app?

Try:
1. Setting your rootviewcontroller manually:
   http://getsharekit.com/support/#issues
2. The bug fix posted here:
   http://github.com/ideashower/ShareKit/issues#issue/24

**Comment by samjarman** [comment]
Hi, its sharing it from a button on a modal view controller.  (I suspect this could be the problem)

**Comment by samjarman** [comment]
No matter where I put [SHK setRootViewController:self.view];
(In the apps root view or the modal view mentioned above) the app crashes.

**Comment by samjarman** [comment]
well to be honest, I just tested it again.. and It worked. Very odd. 

I hope it works for my users is all.

**Comment by ideashower** [comment]
What was the reason for the crash?  Do you know where it crashed?

I'm going to close this for now, if you find out anything else, please let me know.

**Comment by coc** [comment]
The mail view is not dismissed if I test on iOS 4 with ShareKit 0.2.0!
I set [SHK setRootViewController:self.navigationController]; does not help

It is only dismissed in iPhone Simulator, but not on a 3GS

**Comment by jeanfabre** [comment]
Hi,

 I have this issue too, I have the version 0.2.1gm1 , and this thread is a year old so don't know what to think about this. I tried what was suggested here but with no luck.

 My fix is to add [controller dismissModalViewControllerAnimated:YES]; at the end of - (void)mailComposeController:(MFMailComposeViewController_)controller didFinishWithResult:(MFMailComposeResult)result error:(NSError_)error

Not very nice or is it ok?

thanks,

 Jean

**Comment by scurioni** [comment]
Hi Jean, your solution works for me. Thanks!
I don't think it's a bad idea, I've seen this solution somewhere else too.

**Comment by anilnatha** [comment]
Thanks jeanfabre, your solution solved the problem for me too.

**Comment by scruff311** [comment]
I just wanted to add that jeanfabre's solution worked for me also. Thanks!
