### ISSUE TITLE
Get logged in accounts' usernames

### ISSUE THREAD

**Issue by tristanmartin** [ideashower/ShareKit#42]
It would be useful to be able to see what Twitter/Facebook/etc accounts are currently logged in. This goes hand in hand with being able to log out.

**Comment by ideashower** [comment]
Getting usernames:
http://getsharekit.com/docs#authvalues
(Note: You'll need to find documentation on FBConnect to get the values for Facebook)

Logging out:
http://getsharekit.com/docs#logout
