### ISSUE TITLE
Delicious: OAuth not working

### ISSUE THREAD

**Issue by alariccole** [ideashower/ShareKit#44]
Any attempt to use the Delicious service results in an immediate dialog: Request Error: There was a problem requesting authorization from Delicious. 

The console reads the following, citing an issue with the consumer key:
<0x7c0f190 SHKOAuthSharer.m:(108)> tokenRequestTicket Response Body: oauth_problem=consumer_key_rejected

**Comment by alariccole** [comment]
Actually, turns out it was an issue with the way the key was generated on Yahoo's side, not ShareKit ;)

**Comment by Schnyder** [comment]
akaru, how did you resolve the problem?  I'm running into the same message.
