### ISSUE TITLE
Crash on animation.

### ISSUE THREAD

**Issue by andreaf** [ideashower/ShareKit#45]
Hi all, apparently there is a bad access (a released pointer). 
If i choose, in sharing a link:

Share -> More -> Pinboard  (or read it more, or something that pop up the modal controller)

I set the root view controller in the main controller as:

[[SHK currentHelper] setRootViewController:self];

I Have a crash with 

rogram received signal:  “EXC_BAD_ACCESS”.
(gdb) where
#0  0x321068a8 in -[UIWindowController transitionViewDidComplete:fromView:toView:]()
#1  0x3206a1b0 in -[UITransitionView notifyDidCompleteTransition:]()
#2  0x3206a030 in -[UITransitionView _didCompleteTransition:]()
#3  0x32106630 in -[UITransitionView _transitionDidStop:finished:]()
#4  0x32056d78 in -[UIViewAnimationState sendDelegateAnimationDidStop:finished:]()
#5  0x32056c10 in -[UIViewAnimationState animationDidStop:finished:]()
#6  0x31b77064 in run_animation_callbacks ()
#7  0x31b76e6c in CA::timer_callback ()
#8  0x338ae4c2 in CFRunLoopRunSpecific ()
#9  0x338adc1e in CFRunLoopRunInMode ()
#10 0x3434e1c8 in GSEventRunModal ()
#11 0x32002c30 in -[UIApplication _run]()
#12 0x32001230 in UIApplicationMain ()

in in the animation ? can someone confirms ? 

bests
a.

**Comment by ideashower** [comment]
Does it crash before or after the pinboard window is displayed?

**Comment by andreaf** [comment]
Immediately after. But is not related to the pinboard view. Is probably related to the animation effect of multiple modal. 
take a lot at 
http://stackoverflow.com/questions/1173018/multiple-modal-view-transitions-crash-app

Is only in 3.1.3 devices apparently (ipod). Latest Xcode, with target 3.1.3 compile flag.

**Comment by ideashower** [comment]
What version of ShareKit are you using?

Run through the steps here:
http://github.com/ideashower/ShareKit/issues#issue/49

**Comment by andreaf** [comment]
#define SHK_VERSION @"0.1.6"

I will check with the 0.2.0. When was released the 2.0 ? 

thanks.

**Comment by andreaf** [comment]
Just a follow up.
The 0.2.0 is released with the 4.1 beta SDK. Is ok ? is still an unstable / beta sdk.

a.

**Comment by ideashower** [comment]
Changing that to 4.0 should be fine.
