### ISSUE TITLE
<Error>: FT_Load_Glyph failed: glyph 65535: error 6.

### ISSUE THREAD

**Issue by dejo** [ideashower/ShareKit#46]
- Opened the ShareKit project using the latest (3a6a746) source, Xcode 3.2.3 and Base SDK of iPhone Device 4.0
- Build and Run in Simulator
- Sharing Text
- Click share button
- Choose Facebook
- The following error message appears twice in the Console: <Error>: FT_Load_Glyph failed: glyph 65535: error 6.

**Comment by ideashower** [comment]
Is your phone set to use a different locale than English?

**Comment by dejo** [comment]
Nope.

**Comment by dejo** [comment]
Fixed. Seems I forgot to copy over my SHKConfig settings. Funky console message no longer appearing.
