### ISSUE TITLE
xAuth added by twitter, changed 0 to 1, now what?

### ISSUE THREAD

**Issue by samjarman** [ideashower/ShareKit#47]
When selecting twitter from the list, nothing happens - what do I do now?

Do I have to collect the UN and PW of the user or is that handled by SHK?

**Comment by ideashower** [comment]
Is this in the example project or your own?

If you are having problems, a good place to diagnose issues (to make sure they are not related to ShareKit) is by building the example project with your SHKConfig file and testing that it works there.

**Comment by samjarman** [comment]
hm. Good idea. Will try that

**Comment by samjarman** [comment]
Wow.. I was using 0.1.0. - Dont know how I didnt get the latest version.
All works well now.

**Comment by ideashower** [comment]
haha, that would do it.  Glad it got sorted.
