### ISSUE TITLE
Crash on twitter connection if not configured.

### ISSUE THREAD

**Issue by andreaf** [ideashower/ShareKit#51]
Hi there is a EXEC_BAD_ACCESS In the NSString\* SHKLocalizedString(NSString\* key, ...)  
function when you use twitter share.

Open the example project, run the demo, choose twitter. 
No configuration in the config file, plain downloaded source 0.2.0. 

bests
a.

**Comment by ideashower** [comment]
Why are you running it without configuring? :)

**Comment by andreaf** [comment]
ehm hard test :) 
Btw I think that the error is on the return message if the connection has something that is wrong. Probably (but I can check now) same bugs will be if there are (with correct configuration) network problems.

bests
a.

**Comment by ideashower** [comment]
Let me know if this is still a problem after configuring.

**Comment by andreaf** [comment]
Ok apparently with a configuration works. But the problem was related to a not found string in the localization table for the error, not related to the configuration.

bests
a.
