### ISSUE TITLE
Problem in devices without email configured.

### ISSUE THREAD

**Issue by andreaf** [ideashower/ShareKit#52]
hi if the device (ipad, ipod , iphone) has the email program not configured there
are some problems in the "share file". 
Apparently is shown only the "more button". Clicking on the button does not provide effect
but then all the buttons are inconsistent (if i click su cancel facebook is shown for example).

Probably should be checked if the device can send email.

Version 0.2.0 and example project.

bests
a.

**Comment by dejo** [comment]
"Probably should be checked if the device can send email."

I'm pretty sure it already does, inside the canShare class method of SHKMail:
    + (BOOL)canShare
    {
        return [MFMailComposeViewController canSendMail];
    }

**Comment by andreaf** [comment]
mmm, yes but the check should be before. When the Actionsheet is composed ? 
a.

**Comment by dejo** [comment]
AFAIK, it is checked before: it is the first thing that is checked, according to "[Understanding the Share Flow](http://getsharekit.com/docs/#flow)" in the ShareKit Documentation. Are you actually seeing the Email option appear in the ActionSheet when the device can't send email?

**Comment by andreaf** [comment]
no. Only the "more" single button. 
then the status of the actionsheet / alert on ipad is non consistent. 

bests.
a.

**Comment by dejo** [comment]
I'm confused. If email isn't configured on the device and the ActionSheet isn't showing the Email option, what is inconsistent about that?

Also, what do you mean by "the status of the actionsheet" on iPad?

**Comment by andreaf** [comment]
The actionsheet is on iphone. The alert view is on ipad. If there is no email configured there is only a "more" button in the share file. If you press the more button no action is done. Then apparently the buttons became broken or inconsistent. If you press cancel facebook is shown, if you press twitter che action is closed. 

Try to reproduce with an iphone with the email not configured.

**Comment by jeffruediger** [comment]
In the example project, sharing a file -> email -> will fail to send email because validateItem doesn't handle shareType file.  This was repro'ed on the Simulator.

<pre><code>
@class SHKSharer; 

- (BOOL)validateItem
{
    switch (item.shareType) 
    {
        case SHKShareTypeURL:
            return (item.URL != nil);
            break;          
            
        case SHKShareTypeImage:
            return (item.image != nil);
            break;          
            
        case SHKShareTypeText:
            return (item.text != nil);
            break;
    }
    
    return NO;
}
</code></pre>

**Comment by ideashower** [comment]
@fuzzycube what version of ShareKit are you using?

**Comment by ideashower** [comment]
This is fixed in version 0.2.1 (Coming soon)

Thanks guys
