### ISSUE TITLE
Adding services to existing application

### ISSUE THREAD

**Issue by onnoweb** [ideashower/ShareKit#53]
Enabling additional services in a new version of application don't show.

SHK.favoriteSharersForType checks if favoriteSharers is nil and only then builds the array. ShareKit loads favoriteSharers from UserDefaults on startup, hence new services added in an update of the app don't appear.

**Comment by ideashower** [comment]
How did you 'add' the new sharers?

Did you add it to SHKSharers.plist?

Do the new services show if you select 'More' from the actionsheet?

**Comment by onnoweb** [comment]
Heh, trying to remember now...

Yes, I added them to the plist file.

No, they didn't show via 'More' .

**Comment by ideashower** [comment]
Email me one of the custom sharers to questions at getsharekit.com
