### ISSUE TITLE
Double email signatures

### ISSUE THREAD

**Issue by dginsburg** [ideashower/ShareKit#55]
I don't think the Sent from XXX email signature was a good addition to Sharekit. If you already have the standard "Sent from my iPad" signature then you now get two signatures in the email which is pretty tacky. At the minimum this should be configurable in Sharekit but I'd suggest removing it altogether.

**Comment by ideashower** [comment]
I'll make this an option in the next build, thanks.

**Comment by sindresorhus** [comment]
This should be off by default

**Comment by ideashower** [comment]
Added to version 0.2.1 (Which will be out later today)
