### ISSUE TITLE
Register multiple SHKItems for each of Sharers

### ISSUE THREAD

**Issue by mkftr** [ideashower/ShareKit#56]
I want to change SHKItem's text for Email and Twitter.

**Comment by ideashower** [comment]
Can you expand on this?  I'm not sure what you mean.

**Comment by mkftr** [comment]
Thank you for your reply and sorry for missing the detail...
I have a suggestion about SHKActionSheet from my experience.

1) To be able to hold SHKItems for each of Sharers.
In sometimes, you need to modify content to suitable for the Sharer.

2) To be able to show/remove [More] button by setting property.

I modified SHKActionSheet to meet these requirements.
But I would like to know, what do you think about these.

Thanks in advance.

**Comment by ideashower** [comment]
If you think the updates would be useful to other developers, please submit a fork to the project.  Thanks!

**Comment by mkftr** [comment]
Alright! Thanks!
