### ISSUE TITLE
Twitter oAuth sharing in version 0.2.0 does not work

### ISSUE THREAD

**Issue by coc** [ideashower/ShareKit#57]
I use oAuth, and run into "There was an error while sharing" which is called in the following method if quiet == NO. As I can see, quiet is only set to YES in Offline Mode!
- (void)sharer:(SHKSharer *)sharer failedWithError:(NSError *)error shouldRelogin:(BOOL)shouldRelogin
  {
  if (!quiet)
        ......
  }

Can someone help?

**Comment by ideashower** [comment]
Have you properly configured Twitter in SHKConfig.h?

Please see the section on debugging here, you can check to see what Twitter is responding with:
http://github.com/ideashower/ShareKit/issues#issue/49

**Comment by coc** [comment]
I´ve filled out the the define values for twitter.

I get this debug output:

# Reachability Flag Status: WR t----l- networkStatusForFlags

# <0x6768db0 OAMutableURLRequest.m:(227)> OAMutableURLRequest parameters oauth_consumer_key=<consumer_key>&oauth_nonce=<unknown>&oauth_version=1.0&status=TwitterTestMsg

#Reachability Flag Status: WR t----l- networkStatusForFlags

<consumer_key> is the correct key
The <unknown> is a number I don´t know, starting with 78A5B95F-8805-

In my App I use the code:

 NSDictionary *excludedSharers = [NSDictionary dictionaryWithObjectsAndKeys:@"Email", @"SHKMail", nil];
    [[NSUserDefaults standardUserDefaults]  setObject:excludedSharers forKey:@"SHKExcluded"];
    [SHK pushOnFavorites:@"SHKFacebook" forType:SHKShareTypeText];
    SHKItem *item = [SHKItem text:task];  
    SHKActionSheet *actionSheet = [SHKActionSheet actionSheetForItem:item];
    [actionSheet showFromToolbar:self.navigationController.toolbar];

**Comment by coc** [comment]
Oh, it´s not readable, I retry:

"<0x6768db0 OAMutableURLRequest.m:(227)> OAMutableURLRequest parameters oauth_consumer_key=<consumer_key>&oauth_nonce=<unknown>&oauth_version=1.0&status=TwitterTestMsg"

**Comment by coc** [comment]
oauth_nonce=<unknown>

**Comment by coc** [comment]
oauth_nonce is this 78A5B95F-8805-...

**Comment by coc** [comment]
OK, now it worked. I´ve used another Twitter account. 
The first one was the same as the one where I created the Twitter App. Could this be a problem?
