### ISSUE TITLE
Core - SHK.m: Objective-C++ Support Issue

### ISSUE THREAD

**Issue by adamRenny** [ideashower/ShareKit#59]
Currently the ShareKit works with Objective-C, but due to a naming convention the ShareKit does not yet work with Objective-C++.

The problem is a naming issue found on line 128 of SHK.h, located in the core.
It is also found on line 567 of SHK.m.

In this method's declaration, the parameter name "new" is used.  Because this parameter is a keyword in C++, it throws a compiler error when compiled under Objective-C++.

Change the parameter from new to anything but new, and it should compile and function.

**Comment by ideashower** [comment]
Thanks, I'll check this out.

**Comment by ideashower** [comment]
Fixed in version 0.2.1 (which will be released later today)
