### ISSUE TITLE
Better Facebook Sharing options

### ISSUE THREAD

**Issue by gfontenot** [ideashower/ShareKit#63]
Would love to be able to share Text only as a status update, and also be able to post images to my wall, instead of uploading them to an album.

**Comment by gfontenot** [comment]
Ok, I'm a jerk, and had 0.1.6 instead of 0.2.0. So forget the text only thing. But posting an image to the wall is still a must.

**Comment by ideashower** [comment]
You can share images to the wall with 0.2.0.  Did you try the example app?

**Comment by gfontenot** [comment]
I see that I can upload photos to an album, but that's not what I was talking about. I was talking about attaching an image as a piece of media to a status update, which is possible, but the problem is that the photo has to be hosted somewhere. Unless I am missing something in Facebook's API. So I'm not sure how exactly this could be implemented right now.
