### ISSUE TITLE
Problem logging into Twitter with special characters in password

### ISSUE THREAD

**Issue by gfontenot** [ideashower/ShareKit#65]
My twitter password is autogenerated by 1Password, and I am unable to login with it. I know it is the correct password, as I have also typed it in by hand. If I change my password to a basic letters/numbers only password, it's fixed. This happens in both the simulator and on device.

**Comment by ideashower** [comment]
What is one of the 'bad' characters?  It's possible something isn't being encoded correctly.

**Comment by gfontenot** [comment]
I know that there is a percent sign in there. I feel like that could cause problems.

**Comment by gfontenot** [comment]
Just verified. Added a percentage sign to a dummy account password as the only special character, and it failed to sign in.

**Comment by ideashower** [comment]
Thanks for that, I'm hoping to put together another release this week and I'll be sure to get this one in there.

**Comment by ideashower** [comment]
Found the issue, username/password were being double encoded.  Fix will be included in version 0.2.1
