### ISSUE TITLE
Twitter error message

### ISSUE THREAD

**Issue by robjohnsonmba** [ideashower/ShareKit#66]
Okay, I am not getting any errors in the code because the app is not crashing - it just wont post updates to Twitter.  The other services that I am trying to use all work - email, facebook, and tumblr.  But Twitter doesnt work.  It lets me log in, but doesnt let me post an update.  It shows a "Saving to Twitter" message and then it pops up "Error - There was an error while sharing."

I have triple checked the OAuth settings in SHKConfig.h (Consumer Key, Secret, & Callback URL).  I even went back to twitter and had them regenerate the Key and Secret. XAuth is set to 0.  I don't know what else to do.

Oh, and one tiny thing - where do I change the main UIActionSheet title?  I want it to say something other than "Share".  Thanks

**Comment by ideashower** [comment]
Try turning on debug and see what Twitter is responding with in the Console.

SHKActionSheet is just a UIActionSheet so you can change the title the same what you would with a normal UIActionSheet.

Hope that helps!

**Comment by robjohnsonmba** [comment]
I don't really know how to see what Twitter is responding with.  I do know that the ShareKit code is sending up 3 of the little yellow triangles in the code (FBDialog.m - "setFont" is deprecated, FBRequestm - Class "FBXMLHandler does not implement..., SHKTwitterForm.m - UIKeyboardBoundsUserInfoKey is deprecated)

I double  checked to make sure that I have the most up-to-date version of the code.  What should I do?

**Comment by mcgraw** [comment]
Getting the same issue myself... Still poking around to see if anything comes to light. lastError is null so i'm not getting much feedback.

**Comment by ideashower** [comment]
Any more information on this issue?  Going to close it until I hear back.  Thanks guys.

**Comment by robjohnsonmba** [comment]
I just want to point out that this issue was never resolved.

**Comment by mcgraw** [comment]
Looked into this a bit -- 

Contents of data: {"request":"/1/statuses/update.json","error":"Invalid / used nonce"}

**Comment by mcgraw** [comment]
if you do something like the following, you won't crash out on the invalid nonce error -- 

nonce = [[[OAHMAC_SHA1SignatureProvider alloc] signClearText:(NSString *)string withSecret:[NSString stringWithFormat:@"%f", time(NULL)]] retain];

Strange stuff. Wonder what it doesn't like about just the UUID object.

Though this isn't fully ironed out. I still run into an error. HTML is pumped back with the 'Something is technically wrong.' message.
