### ISSUE TITLE
Presentation Style Bug

### ISSUE THREAD

**Issue by darknecromancer** [ideashower/ShareKit#67]
I have noticed that the twitter view has problems when a parent view controller was presented with the page or form presentation style. When presented with one of those two styles, the twitter view loads up, but the text area and the character count are blank. You can send the twitter just fine, it just cant be edited. To reproduce, just present a modal view with either page or form style, then load up sharekit, then try to send a tweet. Obviously this is isolated to the iPad, but its reproducible in both the simulator and on the device.

**Comment by ideashower** [comment]
This will be fixed in 0.2.1 (which is coming out soon).

Thanks!
