### ISSUE TITLE
SHK.h fails Objective-C++ build 

### ISSUE THREAD

**Issue by bryanbonczek** [ideashower/ShareKit#70]
seems the variable "new" conflicts with the C++ keyword of the same name:

void SHKSwizzle(Class c, SEL orig, SEL new);

renaming it fixed the build error

**Comment by bryanbonczek** [comment]
SHK.m should be updated accordingly as well

**Comment by ideashower** [comment]
Fixed in 0.2.1 (coming out soon)

Thanks!
