### ISSUE TITLE
0.2.1 Release SHK.h appears to be out of date

### ISSUE THREAD

**Issue by adamRenny** [ideashower/ShareKit#75]
Just tried the update, but it wouldn't compile.  It looks like the SHK.h wasn't updated or committed, but SHK.m was.

**Comment by ideashower** [comment]
Did you get the copy from http://getsharekit.com/install or pulled from github?

**Comment by adamRenny** [comment]
It was pulled from getsharekit.com/install, but when I checked the current source on github it had the same function declaration for the SHKSwizzle function.  Based on that, I assumed they were the same header files, but they may not be.

**Comment by ideashower** [comment]
Okay I see the problem.  Strange, it compiles for me though.  How are you compiling?

I'll get the fix up right now.  Thanks for the heads up.

**Comment by adamRenny** [comment]
I'm running it in XCode 3.2.3, with iOS 4.0+.

One area of issue was in SHK.m line 35: #import <objc/objc-class.h>

It seems that objc/objc-class.h isn't necessarily recognized by the system immediately.

I had to update the path to be the full path to the header in order for this to work.

**Comment by starphoenix** [comment]
I still have this error.  I don't seem to have objc-class.h anywhere on my computer, and I'm not sure where it was supposed to have come from.  Im using xcode 4.0.2 on mac OS 10.6.7.

**Comment by faisalhok** [comment]
Mm, I am having the same issue, objc-class.h not found error. 
What needs to be done ? Please suggest.

BR; F

**Comment by starphoenix** [comment]
I did manage to resolve this issue on my own by changing 

#import <objc/objc-class.h>   

to

#import <objc/runtime.h>
