### ISSUE TITLE
SHK.h "new" variable breaks compile when mixing with C++

### ISSUE THREAD

**Issue by ghost** [ideashower/ShareKit#76]
Hi,
The following declaration in SHK.h:

```
void SHKSwizzle(Class c, SEL orig, SEL new);
```

causes a compilation error when mixing with c++ (e.g. in a .mm file):

```
<fullpath>/ShareKit/Core/SHK.h:128: error: expected ',' or '...' before 'new'
```

All you have to do is change the variable name from 'new' to anything else.

**Comment by ideashower** [comment]
This was fixed in version 0.2.1.  Make sure you are using the latest version.
