### ISSUE TITLE
Problem with mail when there is no mail account registered

### ISSUE THREAD

**Issue by lpotherat** [ideashower/ShareKit#79]
When there is no mail account registered in the mail application on ios, the ShareKit view controller stills appear and cannot be dismissed. 

We can know if the user has registered an account or not by checking the return value of [[[MFMailComposeViewController alloc] init] autorelease]. This initializer returns nil in that case. So I made those simple lines to correct the bug : 

In SHKMail.m : 

```
- (BOOL)sendMail
{   
MFMailComposeViewController *mailController = [[[MFMailComposeViewController alloc] init] autorelease];
if(mailController!=nil){
    mailController.mailComposeDelegate = self;
    //Some code
    [[SHK currentHelper] showViewController:mailController];
} else {
    [[SHK currentHelper] hideCurrentViewControllerAnimated:YES];
}
```

**Comment by taberrr** [comment]
Hi, thanks for posting this. Would it be a good idea to also modify the return statement to report whether or not it was properly shared? Somthing like:

```
if(mailController!=nil){
    mailController.mailComposeDelegate = self;
    //Some code
    [[SHK currentHelper] showViewController:mailController];
    return YES;
} else {
    [[SHK currentHelper] hideCurrentViewControllerAnimated:YES];
}
return NO;
```

**Comment by lpotherat** [comment]
the function has been patched 

<pre>
if (!mailController) {
// e.g. no mail account registered (will show alert)
[[SHK currentHelper] hideCurrentViewControllerAnimated:YES];
return YES;
}
</pre>

maybe it should return NO in this case

<pre>
if (!mailController) {
// e.g. no mail account registered (will show alert)
[[SHK currentHelper] hideCurrentViewControllerAnimated:YES];
return NO;
}
</pre>
