### ISSUE TITLE
Crash when an error occurs on Twitter oauth

### ISSUE THREAD

**Issue by lpotherat** [ideashower/ShareKit#80]
In SHKOAuthSharer.m in "- (void)tokenRequestTicket:(OAServiceTicket *)ticket didFinishWithData:(NSData *)data " function this line : 
[self tokenRequestTicket:ticket didFailWithError:[SHK error:SHKLocalizedString(@"There was a problem requesting authorization from %@"), [self sharerTitle]]];

should be at least replaced by : 

[self tokenRequestTicket:ticket didFailWithError:[SHK error:SHKLocalizedString(@"There was a problem requesting authorization from %@", [self sharerTitle])]];

in order to put [self sharerTitle] in the arguments of SHKLocalizedString.

**Comment by ideashower** [comment]
This was fixed in version 0.2.1.  Please make sure you are using the latest version.

**Comment by lpotherat** [comment]
sorry for the mistake, i'm going on downloading it :)
