### ISSUE TITLE
Twitter login window disrupts landscape on iPhone

### ISSUE THREAD

**Issue by blondie7575** [ideashower/ShareKit#88]
When the app is in landscape, the SHK Twitter web-login window causes the root view to be shifted down and to the right by half the screen. This bug occurs on iOS3.1.3 and iOS4. It occurs on iPhone 3G and iPhone4, but NOT iPad. This bug is specific to Twitter. The Facebook window(s) work fine.

I've verified that ShareKit is using the correct root view controller. I've tried setting it manually and letting it find one automatically. Once the root view has been moved out of place, it can be corrected by flipping the device 180\* (triggering another autorotation event).

**Comment by blondie7575** [comment]
Correction:  I've narrowed down this bug to something inside presentModalViewController:animated, so it's not ShareKit's fault.

**Comment by gradha** [comment]
I'm not on the latest version of Sharekit, but the twitter view certainly affects the view (there's a small moment when the top bar moves) and after dismissint the twitter modal view scroll messages seem to be handled incorrectly until as you say the device is rotated. This is on an iPad application with the split view controller as root window.

**Comment by blondie7575** [comment]
In my case, I found it was actually due to something I was doing, and just appeared to be a ShareKit issue. presentModalViewController is pretty sensitive about which view you use as the base for the modal, and it can cause view disruptions, autorotation problems, and other visual strangeness. Perhaps you have something similar happening?

**Comment by atash55** [comment]
So what was the problem? Because i am facing the same issue. In the twitter login the login window is in portrait mode and only occupies 14/th of the screen and one can only see the cancel button
