### ISSUE TITLE
SHKDelicious - Not Renewing Expired Tokens

### ISSUE THREAD

**Issue by ideashower** [ideashower/ShareKit#9]

**Comment by dginsburg** [comment]
NSString *s = [[[NSString alloc] initWithData:data encoding:NSUTF8StringEncoding] autorelease];
NSLog(@"%@", s);

<?xml version="1.0" standalone="yes"?>
<result code="no user associated with these credentials" />

**Comment by dginsburg** [comment]
result code="no user associated with these credentials"

**Comment by dginsburg** [comment]
XML got parsed out but result is an element and code is an attribute with the error string. That seems to be the entirety of the document besides the trailing comment.

**Comment by ideashower** [comment]
Not sure what you mean by these 3 comments but if you would like to improve the error handling on the Delicious class the best way is to fork ShareKit, add your patch, and submit a pull request.  Thanks!

**Comment by dginsburg** [comment]
Sorry for my poor comments. I was just trying to provide an example of error output to help whomever addressed this. If I can figure out github I'll check in something better.

**Comment by dginsburg** [comment]
Delicious flat out doesn't work. Yahoo tokens expire after an hour and there is a process for refreshing them that isn't supported in ShareKit. Of course it can be coded and I'm sure someone will do it over time but you should pull this sharer instead of giving the false impression there is a functioning solution.

**Comment by dginsburg** [comment]
This describes the refresh step. Note the necessity of the oauth_session_handle. This will have to be captured and persisted from the first time the token is retrieved. I'd love to have Delicious support but I don't have time right now to implement this.

http://developer.yahoo.com/oauth/guide/oauth-refreshaccesstoken.html

**Comment by ideashower** [comment]
Fixed in version 0.1.5
