### ISSUE TITLE
potential bug: custom fields are not added when tweets are posted

### ISSUE THREAD

**Issue by mikebz** [ideashower/ShareKit#99]
I believe I found a bug.  Here is some code to share a tweet:

```
NSString *someText = @"foobar";
SHKItem *item = [SHKItem text:someText];
[item setCustomValue:@"47.0" forKey:@"lat"];
[item setCustomValue:@"122.0" forKey:@"long"];
[item setCustomValue:@"true" forKey:@"display_coordinates"];

[SHKTwitter shareItem:item];
```

The custom fields don't seem to be getting to Twitter.  When I traced the code it looks like those values never go to be posted to twitter.

In the sendStatus it doesn't look like the custom values are used.
Am I missing something?

**Comment by ideashower** [comment]
Sharers do not use custom values unless programmed to.  If you'd like to have Twitter send custom variables you'll need to modify (or subclass) SHKTwitter to make use of them.

Hope that helps!
